/*
 * Copyright (C) Volition, Inc. 1999.  All rights reserved.
 *
 * All source code herein is the property of Volition, Inc. You may not sell 
 * or otherwise commercially exploit the source or things you created based on the 
 * source.
 *
*/ 

/*
 * $Logfile: /Freespace2/code/MenuUI/fishtank.h $
 * $Revision: 1.1.1.1 $
 * $Date: 2004/08/13 22:47:41 $
 * $Author: Spearhawk $
 *
 * bloop
 *
 * $Log: FISHTANK.H,v $
 * Revision 1.1.1.1  2004/08/13 22:47:41  Spearhawk
 * no message
 *
 * Revision 1.1.1.1  2004/08/13 21:46:41  Darkhill
 * no message
 *
 * Revision 2.0  2002/06/03 04:02:24  penguin
 * Warpcore CVS sync
 *
 * Revision 1.1  2002/05/02 18:03:09  mharris
 * Initial checkin - converted filenames and includes to lower case
 *
 * 
 * 2     8/26/99 9:45a Dave
 * First pass at easter eggs and cheats.
 * 
 *
 * $NoKeywords: $
 */

#ifndef __FISHTANK_H__
#define __FISHTANK_H__

void fishtank_start();
void fishtank_stop();
void fishtank_process();

#endif /* __CREDITS_H__ */
